### ISSUE TITLE
dropdown lists might need overflow css

### ISSUE THREAD

**Issue by m-ando-japan** [kintone/kintone-ui-component#139]
I think dropdown lists might need overflow css. because it can't show all lists in window when too many items are set in list. 

as like this.
```
.kuc-dropdown-sub-container .kuc-list-outer {
    overflow-y: scroll;
    max-height: 400px;
}
```

**Comment by quocphien90** [comment]
It is correspond to new release v0.3.1
f7ec9cd8fa837c40ad68a3abb5b7408edbe69728
