### ISSUE TITLE
Clicking the date component change the date

### ISSUE THREAD

**Issue by oe-trader** [kintone/kintone-ui-component#249]
When set the focus again on the date component, the date changes.

![kuc dateTime click](https://user-images.githubusercontent.com/51394769/64831579-5035c500-d611-11e9-845d-c01c3d0e1c7a.gif)

My environment:
OS : Windows10 x64
Google Chrome: 76.0.3809.132

Thanks,

**Comment by youtr-s** [comment]
I'm sorry to late reply.
This problem has been solved in current version.
Would you please confirm it?

**Comment by oe-trader** [comment]
Hi.

The issue itself seems to have been fixed.

But for a calendar the focus is on the previous day's date.
Also, there seems to be a React warning when set focus on the time.

These are not fatal, but I want they will be fixed in future updates.
