### ISSUE TITLE
 Default data is not reflected

### ISSUE THREAD

**Issue by miko-hirai** [kintone/kintone-ui-component#336]
tableに行追加した時、以下の条件の場合、defaultDataが新しい行に反映されません。
・setValueした後
・defaultDataに空文字を設定した時

上記のケースでは追加した次の行の値がそのまま残ります。
最終行で追加した場合は空白行が追加されます。

掲載されているsetValue()のサンプルコードの11行目を'default text field value' →’’（空文字）に変更し、事象再現しました。
ご確認お願いします。

![src](https://user-images.githubusercontent.com/58278149/69779374-28ef9c80-11eb-11ea-85a3-fc4b1aaa4011.png)

**Comment by youtr-s** [comment]
@miko-hirai 
issue登録ありがとうございます。
こちら開発チームでも動作を確認したところ不具合である事がわかりましたので、
次回アップデート時に修正対応を行いたいと思います。
ご不便をおかけしますがアップデートまで少々お待ち下さい。

**Comment by youtr-s** [comment]
@miko-hirai 
こちら先日のアップデートで不具合改修が完了いたしました。
https://github.com/kintone/kintone-ui-component/releases/tag/v0.5.0
