### ISSUE TITLE
NotifyPopup is not centered

### ISSUE THREAD

**Issue by kawamurayuto** [kintone/kintone-ui-component#404]
素晴らしいプロダクトをありがとうございます。日本語で失礼します。

本題ですが、Chrome ver 79 にて NotifyPopup  が中央に表示されません。

下記CSSを調べましたが、
https://github.com/kintone/kintone-ui-component/blob/master/src/css/NotifyPopup.css

```
.kuc-notify {
    user-select: none;
    top: 30px;
    left: 50%;
    transform: translate(-50%);
```

```
@keyframes kuc-notify-fade-in {
    0% {opacity: 0; transform: translate3d(0,-16px,0);}
    100% {opacity: 1; transform: translate3d(0,0,0);}
```

`.kuc-notify` の `transform: translate(-50%);` の設定が、アニメーションの `translate3d` で x 軸が `0` に上書きされていることが原因かと思われます。

 どうぞよろしくお願いします。

**Comment by youtr-s** [comment]
issueの登録ありがとうございます。
ご指摘頂いた問題ですが、開発側でも認識しており現在対応中ですので修正まで少々お待ち下さい。

**Comment by youtr-s** [comment]
@kawamurayuto 
こちらご連絡が遅くなり申し訳ありません。
先日リリースされたv0.7.0でご指摘いただいた不具合の修正を行いましたのでご確認下さい。
https://github.com/kintone/kintone-ui-component/commit/3820079f562033f96979a54fcda79d0f16990853
