### ISSUE TITLE
MultipleChoice occurs "invalid function arguments" error

### ISSUE THREAD

**Issue by asaga** [kintone/kintone-ui-component#9]
* English is below

MultipleChoiceで、 選択されている（チェックが付いている）要素をremoveItem()するとinvalid function argumentsが発生します。

---

Using MultipleChoice and deleting (removeItem()) the selected  item, it seems that an "invalid function argument" error occurs.

**Comment by asaga** [comment]
Environment where error occurs
https://jsfiddle.net/koji817/Lxhkfgun/49/

1. Click the Run button
2. Select Orange-1
3. Click the GO! link

**Comment by trung-doan** [comment]
@asaga 
We will fix this error on next version.
Thank you very much!

**Comment by trung-doan** [comment]
@asaga 
We have fixed this issue on new version (0.1.3)
https://www.npmjs.com/package/kintone-ui-component/v/0.1.3
Please let me know if there is any problem.

Thank you!
